### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 09williamsad** [Coreforge/blender-halo-infinite#1]
For some models/textures, when importing dependencies this error occurs:
`ASG Control map: objects\characters\elite\bitmaps\elite_officer\elite_officer_torso_covenant_001\elite_officer_torso_covenant_001_asg_control
Texture File name: elite_officer_torso_covenant_001_asg_control{pc}.bitmap
Reading texture block D:\HIUnpack/__chore/pc__/objects/characters/elite/bitmaps/elite_officer/elite_officer_torso_covenant_001/elite_officer_torso_covenant_001_asg_control{pc}.bitmap[3_bitmap_resource_handle.chunk3]
Python: Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-master\renderModel.py", line 764, in execute
    openRenderModel(f)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-master\renderModel.py", line 518, in openRenderModel
    materials[part.material_index].readMaterial(self.root_folder + "/" + part.material_path.replace("\\","/").replace("//","/") + ".material",self.root_folder,import_settings)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-master\Material.py", line 67, in readMaterial
    tex.readTexture(root + "/__chore/pc__/" + self.string_table.strings[idx].replace("\\","/") + "{pc}.bitmap", path.split("/")[-1]+".asg",import_settings)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-master\Texture.py", line 343, in readTexture
    print(f"Width: {width} Height: {height} Format: {DXGI_FORMAT[format]} {hex(format)}")
IndexError: list index out of range
location: <unknown location>:-1`

This specific model works fine when not importing dependencies.
Sample files: https://mega.nz/folder/vOBEkThQ#mGg0GFC70IDuibkLj340WA

**Comment by Coreforge** [comment]
Looks like the format field is only 16 bits wide instead of 32. The branch [texture_#1](https://github.com/Coreforge/blender-halo-infinite/tree/texture_%231) should have it fixed

**Comment by 09williamsad** [comment]
That resolved the initial issue, but now after a few minutes the importer tries to import a texture that does not exist.
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\HIUnpack/__chore/pc__/__chore/gen__/shaders/surfaces/cvw/matsys/cvw_matsys_l1{10}_448{pc}.bitmap'

I have the game files extracted and there is no cvw_matsys_l1{10}_448{pc}.bitmap anywhere.

**Comment by Coreforge** [comment]
The chore/pc/chore/gen path seems wrong, but there is a file with that name, but it's in chore/gen/pc, and ends with .shadervariant. Which material/model are you trying to import? There probably is something wrong in the material code (it's taking a certain hash as a texture entry, but it's probably just a dependency entry or something like that then, and just checking the field I use to identify the texture type isn't enough). Can you also post the console output (or just a couple lines before the exception)?

**Comment by 09williamsad** [comment]
ASG Control map: objects\characters\elite\bitmaps\elite_zealot\helmet\elite_zealot_helmet_covenant_001\elite_zealot_helmet_covenant_001_asg_control
Texture File name: elite_zealot_helmet_covenant_001_asg_control{pc}.bitmap
Reading texture block D:\HIUnpack/__chore/pc__/objects/characters/elite/bitmaps/elite_zealot/helmet/elite_zealot_helmet_covenant_001/elite_zealot_helmet_covenant_001_asg_control{pc}.bitmap[2_bitmap_resource_handle.chunk2]
Width: 1024 Height: 1024 Format: DXGI_FORMAT_BC1_UNORM 0x47
Mask 1 Control map: objects\characters\elite\bitmaps\elite_zealot\helmet\elite_zealot_helmet_covenant_001\elite_zealot_helmet_covenant_001_mask_1_control
Texture File name: elite_zealot_helmet_covenant_001_mask_1_control{pc}.bitmap
Reading texture block D:\HIUnpack/__chore/pc__/objects/characters/elite/bitmaps/elite_zealot/helmet/elite_zealot_helmet_covenant_001/elite_zealot_helmet_covenant_001_mask_1_control{pc}.bitmap[2_bitmap_resource_handle.chunk2]
Width: 1024 Height: 1024 Format: DXGI_FORMAT_BC1_UNORM 0x47
Mask 0 Control map: objects\characters\elite\bitmaps\elite_zealot\helmet\elite_zealot_helmet_covenant_001\elite_zealot_helmet_covenant_001_mask_0_control
Texture File name: elite_zealot_helmet_covenant_001_mask_0_control{pc}.bitmap
Reading texture block D:\HIUnpack/__chore/pc__/objects/characters/elite/bitmaps/elite_zealot/helmet/elite_zealot_helmet_covenant_001/elite_zealot_helmet_covenant_001_mask_0_control{pc}.bitmap[2_bitmap_resource_handle.chunk2]
Width: 1024 Height: 1024 Format: DXGI_FORMAT_BC1_UNORM 0x47
Normal map: objects\characters\elite\bitmaps\elite_zealot\helmet\elite_zealot_helmet_covenant_001\elite_zealot_helmet_covenant_001_normal
Texture File name: elite_zealot_helmet_covenant_001_normal{pc}.bitmap
Reading texture block D:\HIUnpack/__chore/pc__/objects/characters/elite/bitmaps/elite_zealot/helmet/elite_zealot_helmet_covenant_001/elite_zealot_helmet_covenant_001_normal{pc}.bitmap[3_bitmap_resource_handle.chunk3]
Width: 1024 Height: 1024 Format: DXGI_FORMAT_BC5_SNORM 0x54
String  has no valid index and will be ignored
String  has no valid index and will be ignored
String  has no valid index and will be ignored
String objects\characters\elite\bitmaps\elite_zealot\helmet\elite_zealot_helmet_covenant_001\elite_zealot_helmet_covenant_001_asg_control has no valid index and will be ignored
String  has no valid index and will be ignored
String  has no valid index and will be ignored
String  has no valid index and will be ignored
String  has no valid index and will be ignored
ASG Control map: objects\characters\elite\bitmaps\elite_zealot\helmet\elite_zealot_helmet_covenant_001\elite_zealot_helmet_covenant_001_asg_control
Texture File name: elite_zealot_helmet_covenant_001_asg_control{pc}.bitmap
Reading texture block D:\HIUnpack/__chore/pc__/objects/characters/elite/bitmaps/elite_zealot/helmet/elite_zealot_helmet_covenant_001/elite_zealot_helmet_covenant_001_asg_control{pc}.bitmap[2_bitmap_resource_handle.chunk2]
Width: 1024 Height: 1024 Format: DXGI_FORMAT_BC1_UNORM 0x47
Mask 1 Control map: __chore\gen__\shaders\surfaces\cvw\matsys\cvw_matsys_l1{10}_448
Python: Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-texture_-1\renderModel.py", line 764, in execute
    openRenderModel(f)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-texture_-1\renderModel.py", line 518, in openRenderModel
    materials[part.material_index].readMaterial(self.root_folder + "/" + part.material_path.replace("\\","/").replace("//","/") + ".material",self.root_folder,import_settings)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-texture_-1\Material.py", line 75, in readMaterial
    tex.readTexture(root + "/__chore/pc__/" + self.string_table.strings[idx].replace("\\","/") + "{pc}.bitmap", path.split("/")[-1]+".mask_1",import_settings)
  File "C:\Users\Adam\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-texture_-1\Texture.py", line 300, in readTexture
    with open(path,'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\HIUnpack/__chore/pc__/__chore/gen__/shaders/surfaces/cvw/matsys/cvw_matsys_l1{10}_448{pc}.bitmap'

location: <unknown location>:-1

**Comment by Coreforge** [comment]
So it's trying to read a control 1 mask. I don't have the material file, so I can't check that, but I could add something that just ignores the entry if the path starts with __chore\gen__

**Comment by 09williamsad** [comment]
[material.zip](https://github.com/Coreforge/blender-halo-infinite/files/7706817/material.zip)

**Comment by Coreforge** [comment]
Those are the shader files. You can uncomment `#print(path)` in Material.py (line 34) to have it print the path of the .material file to the console.

**Comment by 09williamsad** [comment]
[material2.zip](https://github.com/Coreforge/blender-halo-infinite/files/7706936/material2.zip)

**Comment by Coreforge** [comment]
Those should be the right ones. I'll look into them tomorrow.

**Comment by Coreforge** [comment]
Pushed another update on dev that should hopefully fix it. Most of the texture entries have the bitmap tag, but this one didn't, so I added a check for that. I left it out though on the asg map, since those never had the tag, which is a bit odd.
